### ISSUE TITLE
First MVP - Build out complete & tested documentation

### ISSUE THREAD

**Issue by usrbinkat** [CodeSparta/codectl.github.io#5]
Assess to verify MVP1 example doc is alive and accurate

- OpenShift 4.5+ on AWS AirGapped (TESTING)
- OpenShift 4.5+ on AWS AirGapped +infrastructure/terraform, Includes Route53

**Comment by this-funk** [comment]
OpenShift 4.3 on AWS AirGapped GovCloud
OpenShift 4.5+ on AWS AirGapped (TESTING)
OpenShift 4.5+ on AWS AirGapped +infrastructure/terraform, Includes Route53
OpenShift 4.5+ on AWS AirGapped FENCES
